### ISSUE TITLE
where is default download path for paper

### ISSUE THREAD

**Issue by Johnson-yue** [temken/comparxiv#14]
Hi, thank you for your sharing
I used it to compare starganv2 paper with different version, v1 and v2
so :
`comparxiv 1912.01865 1 2`
then it download the paper for v1 version and v2 version
but maybe I network have some trouble so , it failed to download v2 version
then I re-run the command:
`comparxiv 1912.01865 1 2` it not work, I think I should remove some download file and re-download it ??

**Comment by temken** [comment]
That is peculiar. The download works fine for this paper on my machine. There might be some faulty temporary files that were not deleted if comparxiv was aborted.

Check if there is a hidden folder called ```/.temp_comparxiv/``` in the folder from where you run the command. If so, delete it and try again.

**Comment by Johnson-yue** [comment]
ok， I will try， and would you update for fix it ？？
if download file is failed，then remove temporary file？？

**Comment by temken** [comment]
I do not see that anything needs to be fixed at this point. At the end of any comparxiv run, successful or not, the temporary folder gets deleted, unless explicitly stated otherwise in the command line options. You can see it [here](https://github.com/temken/comparxiv/blob/01bca58e29545727f76c4e9bd03bb271e60115f4/comparxiv/comparxiv.py#L120-L122).

So my guess is that either you or the system aborted the program prematurely. Since I cannot reproduce the error, I don't see how that could be fixed. If you have an idea, please let me know.

**Comment by Johnson-yue** [comment]
ok, I will try it again, and if I see the bug again, I will show you log  and reopen this issue, thank you
